In [3]:
from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [7]:
kmeans = []
kmeans_sil = []

In [8]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

for i in range(8, 13):
    kmeans_i = KMeans(n_clusters=i)
    kmeans_i.fit(X)
    sil = silhouette_score(X, kmeans_i.labels_)
    kmeans.append(kmeans_i)
    kmeans_sil.append(sil)

In [9]:
print(kmeans_sil)

[0.07339257175586465, 0.05683395069909048, 0.05869201052848778, 0.05834321752619889, 0.05818055304728226]


In [10]:
import pickle
with open('kmeans_sil.pkl', 'wb') as fp:
    pickle.dump(kmeans_sil, fp)

In [11]:
kmeans_10 = kmeans[2]
y_pred = kmeans_10.predict(X)

In [12]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y, y_pred)

In [13]:
print(conf)

[[5053    2  290   39    9    4  162    7   72 1265]
 [   0 4293    8    7   10 3526    7   11    8    7]
 [  57  423  323  216 4863  436  147   78  201  246]
 [  24  449 4581  193  216   58   31   45 1083  461]
 [   9  178    0 3728   29  234  168 2173   17  288]
 [  60  155 2129  432    7  280   67  215 1156 1812]
 [  71  190   38   67   53   45 4326    4   14 2068]
 [  21  372    6 2094   53  314    4 4399   18   12]
 [  36  335 1212  208   53  330   51  193 4115  292]
 [  51  261   87 3462   19   95   16 2849   87   31]]


In [19]:
import numpy as np
arg_maxes = list(set(np.argmax(row) for row in conf))
kmeans_argmax = sorted(arg_maxes)
kmeans_argmax

[0, 1, 2, 3, 4, 6, 7, 8]

In [24]:
with open('kmeans_argmax.pkl', 'wb') as fp:
    pickle.dump(kmeans_argmax, fp)

In [34]:
distances = [np.linalg.norm(X[i] - x2) for i in range(300) for x2 in X if not (X[i]==x2).all()]
min_distances = sorted(distances)[:10]

In [35]:
mean = np.mean(min_distances[:3])
min_distances

[279.26152617215286,
 304.37641170103836,
 317.5893575043093,
 328.7658741414626,
 333.4546445920344,
 352.89800226127664,
 355.1774204534967,
 358.07401469528617,
 359.64287842247063,
 360.42474942767177]

In [ ]:
from sklearn.cluster import DBSCAN
dbscan_len = []
for eps in np.arange(mean, mean*1.1, mean*0.04):
    dbscan = DBSCAN(eps=eps)
    dbscan.fit(X)
    dbscan_len.append(len(set(dbscan.labels_)))

In [ ]:
with open('dbscan_len.pkl', 'wb') as fp:
    pickle.dump(dbscan_len, fp)

In [38]:
dbscan_len

[70000, 70000, 70000]